namespace DisconnectedAdoDemo.Models;

public class Product
{
    public int Id { get; set; }         // will be auto-generated by DB
    public string Name { get; set; } = "";
    public decimal Price { get; set; }
}