CREATE DATABASE IF NOT EXISTS ado_demo;

USE ado_demo;

CREATE TABLE IF NOT EXISTS products(
Id INT PRIMARY KEY AUTO_INCREMENT ,
name VARCHAR(100)NOT NULL,
price DECIMAL(10,2)NOT NULL
);

CREATE TABLE IF NOT EXISTS cart(
Id INT PRIMARY KEY AUTO_INCREMENT ,
name VARCHAR(100)NOT NULL,

);
