@rootURL = http://localhost:5130

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/books
accept: application/json

###
GET {{rootURL}}/api/books/1
accept: application/json